name: MOCH_WEB
description: QuickStart
version: 0.0.1
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  angular2: ^2.1.1
  angular2_components: ^0.2.0
  http: ^0.11.0
  stream_transformers: ^0.3.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'    
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'    
- dart_to_js_script_rewriter
